# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 09:57
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_auto_20170327_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
