# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 03:23
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_auto_20170401_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
