# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_arn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
